server:
  port: 9009
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dev
    gateway:
      routes:
        - id: gateway-product #路由标识，必须是唯一的
          uri: lb://product #路由的目标地址
          predicates: #路由断言，判断请求是否符合规则
            - Path=/product/** #路径判断，判断路径是否是/product开头，如果是就符合
            #总体的流程是：id可以随便写，但是必须是唯一的，根据断言来判断（predicates）判断条件有很多，如上-Path，
            #如果路劲是以/product开头那么就是符合条件就路由到uri填写的地址上。